### ISSUE TITLE
اجرا نشدن روی همه سرور ها 

### ISSUE THREAD

**Issue by sirvan1133** [XuVix/Monitoring_Bot#1]
من روی 4 تا سرور نصب کردم فقط روی یکیشون لاگهاش میاد به تلگرام

**Comment by TheMrMobin** [comment]
> من روی 4 تا سرور نصب کردم فقط روی یکیشون لاگهاش میاد به تلگرام 

فایروال که روشن نیست؟

**Comment by XuVix** [comment]
https://github.com/XuVix/Monitoring_Bot/commit/27acad7bf37aacf8dcdb3109ef1791ef75ad9c03

https://github.com/XuVix/Monitoring_Bot/commit/723b09e019a620a2756128f38c29e90909c5791c


FIXED ✅
